# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new-window.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(754, 588)
        Dialog.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(81, 0, 135, 255),stop:0.427447 rgba(41, 61, 132, 235), stop:1 rgba(155, 79, 165, 255))\n"
"")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(20, 10, 721, 561))
        self.frame.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"border: 2px solid rgba(255, 255, 255, 40);\n"
"border-radius: 7px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 70, 721, 51))
        font = QtGui.QFont()
        font.setFamily("Orpheus")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: none;\n"
"border: none;\n"
"color: black;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(0, 170, 721, 51))
        font = QtGui.QFont()
        font.setFamily("Orpheus")
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: none;\n"
"border: none;\n"
"color: black;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(0, 220, 721, 51))
        font = QtGui.QFont()
        font.setFamily("Orpheus")
        font.setPointSize(22)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: none;\n"
"border: none;\n"
"color: black;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(0, 270, 721, 51))
        font = QtGui.QFont()
        font.setFamily("Orpheus")
        font.setPointSize(22)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: none;\n"
"border: none;\n"
"color: black;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(0, 320, 721, 51))
        font = QtGui.QFont()
        font.setFamily("Orpheus")
        font.setPointSize(22)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: none;\n"
"border: none;\n"
"color: black;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(0, 370, 721, 51))
        font = QtGui.QFont()
        font.setFamily("Orpheus")
        font.setPointSize(22)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: none;\n"
"border: none;\n"
"color: black;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(0, 510, 721, 51))
        font = QtGui.QFont()
        font.setFamily("Orpheus")
        font.setPointSize(22)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"color: black;\n"
"background-color: rgba(255,255,255, 30);\n"
"border: 2px solid rgba(255,255,255,40);\n"
"border-radius: 7px;\n"
"width:230px;\n"
"height: 50px\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/reply_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Правила"))
        self.label_2.setWhatsThis(_translate("Dialog", "<html><head/><body><p align=\"justify\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Roboto,Open Sans,Helvetica Neue,Noto Sans Armenian,Noto Sans Bengali,Noto Sans Cherokee,Noto Sans Devanagari,Noto Sans Ethiopic,Noto Sans Georgian,Noto Sans Hebrew,Noto Sans Kannada,Noto Sans Khmer,Noto Sans Lao,Noto Sans Osmanya,Noto Sans Tamil,Noto Sans Telugu,Noto Sans Thai,sans-serif\'; font-size:13px; color:#000000; background-color:#ffffff;\">Два игрока ходят поочередно на четырехугольной доске с гексагональной сеткой, синими или красными фишками (начинает первым ходить игрок с синими фишками). Задача игроков провести линию к противоположным сторонам своего цвета.</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "Два игрока ходят поочередно на четырехугольной "))
        self.label_3.setText(_translate("Dialog", "доске с гексагональной сеткой, синими или"))
        self.label_4.setText(_translate("Dialog", "красными фишками (начинает первым ходить"))
        self.label_5.setText(_translate("Dialog", "игрок с синими фишками). Задача игроков провести"))
        self.label_6.setText(_translate("Dialog", "линию к противоположной сторонам своего цвета."))
        self.pushButton.setText(_translate("Dialog", "Выйти"))
import res_new_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
